plugins {
    id 'java-library'
    id 'java-gradle-plugin'
    id 'maven-publish'
}

apply from: 'gradle/defaultBuildProperties.gradle'

group = 'no.statkart.launcher'
version = launcher_version

repositories {
    mavenLocal()
    maven {
        url maven_repo
    }
}

sourceSets {
    client
    server
    test {
        compileClasspath += sourceSets.client.output
        compileClasspath += sourceSets.server.output
        runtimeClasspath += sourceSets.client.output
        runtimeClasspath += sourceSets.server.output
    }
}

dependencies {
    clientImplementation 'com.threerings.getdown:getdown-launcher:1.8.6@jar'
    serverCompileOnly 'javax.servlet:javax.servlet-api:3.1.0'
    implementation 'com.threerings.getdown:getdown-core:1.8.6'

    testImplementation 'junit:junit:4.13.1'
    testImplementation 'org.assertj:assertj-core:3.18.1'
    testImplementation 'org.mockito:mockito-core:3.5.7'

    api 'org.apache.commons:commons-compress:1.20'
    api 'net.jsign:jsign-core:3.1'
    api 'org.tukaani:xz:1.8'
}

gradlePlugin {
    plugins {
        launcherPlugin {
            //noinspection GroovyAssignabilityCheck
            id = 'no.statkart.launcher'
            //noinspection GroovyAssignabilityCheck
            implementationClass = 'no.statkart.launcher.gradle.plugin.LauncherPlugin'
        }
    }
}

// Minimumskrav til java for å bygge launcher
java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

// Minimumskrav til java for å bygge og kjøre klientdelen av launcher
compileClientJava {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

// Minimumskrav til java for å bygge og kjøre tjenerdelen av launcher
compileServerJava {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs << '-Xlint:all' << '-Werror'
}

task clientJar(type: Jar) {
    archiveAppendix.set('client')
    from sourceSets.client.output
    destinationDirectory.set(file('build/client/lib'))
    manifest {
        attributes(
                'Implementation-Title': 'Kartverkets launcher client',
                'Implementation-Version': archiveVersion.get()
        )
    }
}

task serverJar(type: Jar) {
    archiveAppendix.set('server')
    from sourceSets.server.output
    destinationDirectory.set(file('build/server/lib'))
    manifest {
        attributes(
                'Implementation-Title': 'Kartverkets launcher server',
                'Implementation-Version': archiveVersion.get()
        )
    }
}

jar {
    // Pluginen trenger denne, men den ligger pt ikke i maven
    into('lib/packr') {
        from 'lib/packr-all-4.0.0.jar'
    }
    into('jdk') {
        from('jdk') {
            include 'fonts/*'
        }
    }
    into('lib/client') {
        from(clientJar)
        from(configurations.clientRuntimeClasspath)
    }
    into('lib/server') {
        from(serverJar)
        from(configurations.serverRuntimeClasspath)
    }
    manifest {
        attributes(
                'Implementation-Title': 'Kartverkets launcher plugin',
                'Implementation-Version': archiveVersion.get(),
        )
    }
}

task sourceJar(type: Jar) {
    from sourceSets.main.allSource
    from sourceSets.client.allSource
    from sourceSets.server.allSource
    classifier "sources"
}

publishing {
    publications.all {
        if (it.name == 'pluginMaven') artifact sourceJar
    }
    repositories {
        String mavenUpload = System.getenv('MAVEN_PUBLISH')
        maven {
            if (mavenUpload) {
                String creds = mavenUpload.split('@|//')[1]
                url mavenUpload.replace(creds.concat('@'), '') // url kommer i konsoll - ikke ha credentials der
                credentials {
                    username creds.split(':')[0] ?: ""
                    password creds.split(':')[1] ?: ""
                }
            }
        }
    }
}