plugins {
    id 'java-library'
    id 'maven-publish'
}

// Launcheren skal kompileres med og kjøres av denne java-versjonen.
// Klienten som launcheren starter opp skal kjøres av denne java-versjonen.
sourceCompatibility = JavaVersion.VERSION_12

apply from: 'gradle/defaultBuildProperties.gradle'
apply from: 'gradle/libraries.gradle'

group = 'no.statkart.launcher'
version = launcher_version

repositories {
    mavenLocal()
    maven {
        url maven_repo
    }
}

sourceSets {
    client
    server
}

// Server-kildekoden skal deployes i en servlet-container.
// For Kartverket betyr dette per i dag weblogic - som kjører på java 1.8.
compileServerJava {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

dependencies {
    clientImplementation libraries.getdown_launcher
    serverImplementation libraries.getdown_core
    serverImplementation libraries.slf4j_api
    serverCompileOnly libraries.servlet_api

    api libraries.commons_compress
    api libraries.jsign
    api libraries.seven_z

    implementation gradleApi()
    implementation files('lib/packr-2.0-SNAPSHOT.jar')
}

task clientJar(type: Jar) {
    archiveName "launcher-client-${archiveVersion.get()}.jar"
    from sourceSets.client.output
    destinationDir file('build/client/lib')
    manifest {
        attributes(
                'Implementation-Title': 'Kartverkets launcher client',
                'Implementation-Version': archiveVersion.get()
        )
    }
}

task serverJar(type: Jar) {
    archiveName "launcher-server-${archiveVersion.get()}.jar"
    from sourceSets.server.output
    destinationDir file('build/server/lib')
    manifest {
        attributes(
                'Implementation-Title': 'Kartverkets launcher server',
                'Implementation-Version': archiveVersion.get()
        )
    }
}

task clientJarDependencies(type: Copy) {
    dependsOn configurations.clientRuntimeClasspath
    from configurations.clientRuntimeClasspath
    into 'build/client/lib'
}

task serverJarDependencies(type: Copy) {
    dependsOn configurations.serverRuntimeClasspath
    from configurations.serverRuntimeClasspath
    into 'build/server/lib'
}

task downloadWindowsJdk { doLast { downloadJdk(jdk_windows_url) } }
task downloadLinuxJdk { doLast { downloadJdk(jdk_linux_url) } }
task downloadOSXJdk { doLast { downloadJdk(jdk_osx_url) } }

jar {
    dependsOn clientJar
    dependsOn serverJar
    dependsOn clientJarDependencies
    dependsOn serverJarDependencies
    dependsOn downloadWindowsJdk
    dependsOn downloadLinuxJdk
    dependsOn downloadOSXJdk
    from {
        // Pluginen trenger denne, men den ligger ikke i maven
        zipTree(file('lib/packr-2.0-SNAPSHOT.jar'))
    }
    into('jdk') {
        from('build/jdk')
        from('jdk') {
            include 'fonts/*'
        }
    }
    into('lib/client') { from('build/client/lib') }
    into('lib/server') { from('build/server/lib') }
    manifest {
        attributes(
                'Implementation-Title': 'Kartverkets launcher',
                'Implementation-Version': archiveVersion.get()
        )
    }
}

static void downloadJdk(String url) {
    new File('build/jdk/').mkdirs()
    def f = new File('build/jdk/' + urlTilFilnavn(url))
    if (!f.exists()) {
        new URL(url).withInputStream { i -> f.withOutputStream { it << i } }
    }
}

static String urlTilFilnavn(String url) {
    return java.nio.file.Paths.get(new URL(url).getPath()).getFileName().toString()
}

publishing {
    publications {
        artifakt(MavenPublication) {
            from components.java
        }
    }
    repositories {
        String mavenUpload = System.getenv('MAVEN_PUBLISH')
        maven {
            if (mavenUpload) {
                String creds = mavenUpload.split('@|//').getAt(1)
                url mavenUpload.replace(creds.concat('@'), '') // url kommer i konsoll - ikke ha credentials der
                credentials {
                    username creds.split(':').getAt(0) ?: ""
                    password creds.split(':').getAt(1) ?: ""
                }
            }
        }
    }
}
