#!groovy

/**
 * Pipeline for å release artifakter for launcher til Maven repository.
 * Versjonen som skal releases må være tagget med versjonsnummeret i Git.
 */

@Library('common') _

pipeline {
    agent {
        node {
            label 'matrikkelen'
        }
    }

    tools {
        jdk 'Java 11 Latest'
    }

    environment {
        // Forhindre samtidighetsproblemer
        // Tilsvarer "Force GRADLE_USER_HOME to use workspace" i "Gradle plugin"
        GRADLE_USER_HOME = "${WORKSPACE}/gradle"

        GRADLEW_OPTIONS =
            "-Dmaven.repo.local='${WORKSPACE}/.m2/repository' " +
            "-Dfile.encoding=UTF8 " +
            "--no-daemon " +
            "--stacktrace"

        // URI for repository som det skal deployes til
        // Denne må være på formen http(s)://<brukernavn>:<passord>@<repository>
        MAVEN_PUBLISH = credentials('MAVEN_DEPLOY_RELEASES')
    }

    options {
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: '15'))
        disableConcurrentBuilds()
        skipStagesAfterUnstable()
    }

    parameters {
        string(
                name: 'version',
                defaultValue: '',
                description: 'Versjonen som skal publiseres, f.eks. "1.2.1". Merk at denne må være samme som taggen i Git.',
                trim: true
        )
    }

    stages {
        stage('Valider') {
            steps {
                script {
                    if (params.version == '') {
                        currentBuild.result = 'ABORTED'
                        error('Versjon må oppgis!')
                    }
                }
            }
        }

        stage('Prepare launcher') {
            steps {
                // Den neste linjen kan fjernes etter hvert, men t.o.m. 1.2.12 må dette gjøres
                sh 'chmod +x gradlew'
                sh "./gradlew ${GRADLEW_OPTIONS} clean"
            }
        }

        stage('Publish launcher') {
            steps {
                sh "./gradlew ${GRADLEW_OPTIONS} publish -Plauncher_version=${params.version}"
            }
        }
    }

    post {
        success {
            deleteDir()
        }
        cleanup {
            sendNotifications(currentBuild.result, 'launcher')
        }
    }
}
