#!groovy

/**
 * Pipeline for å bygge launcher
 */

@Library('common') _

pipeline {
    agent {
        node {
            label 'matrikkelen'
        }
    }

    tools {
        jdk 'Java 11 Latest'
    }

    environment {
        GRADLEW_OPTIONS =
            "-Dfile.encoding=UTF8 " +
            "--refresh-dependencies " +
            "--stacktrace"
    }
    options {
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: '15'))
        disableConcurrentBuilds()
        skipStagesAfterUnstable()
    }

    stages {
        stage('Prepare launcher') {
            steps {
                // Den neste linjen kan fjernes etter hvert, men t.o.m. 1.2.12 må dette gjøres
                sh 'chmod +x gradlew'
                sh "./gradlew ${GRADLEW_OPTIONS} clean"
            }
        }

        stage('Build launcher') {
            steps {
                sh "./gradlew ${GRADLEW_OPTIONS} assemble"
            }
        }

        stage('Test launcher') {
            steps {
                sh "./gradlew ${GRADLEW_OPTIONS} check"
            }
            post {
                always {
                    junit '**/build/test-results/*/*.xml'
                }
            }
        }
    }

    post {
        success {
            deleteDir()
        }
        cleanup {
            sendNotifications(currentBuild.result, 'launcher')
        }
    }
}
